name: 'Environment settings interface'
description: 'Get information about cluster by environment private action'
author: hello@cloudposse.com
branding:
  icon: 'settings'
  color: 'white'
inputs:
  implementation_repository:
    description: 'Repository with Environment action implementation'
    required: true
  implementation_path:
    description: 'Repository path with Environment action implementation'
    required: true
  implementation_ref:
    description: 'Ref of environment action implementation'
    required: true
  implementation_github_pat:
    description: 'GitHub PAT that allows fetching environment action implementation'
    required: true
  environment:
    description: "The environment name"
    required: true
  namespace:
    description: "The namespace"
    required: true
  repository:
    description: "The repository name"
    required: true
  config-app-name:
    description: "The application name for configuration purposes"
    required: true
  tenant:
    description: "The tenant for the deployment"
    required: true
outputs:
  name:
    description: "The environment name"
    value: ${{ steps.environment.outputs.name }}
  region:
    description: "The region"
    value: ${{ steps.environment.outputs.region }}
  service-ssm-role:
    description: "The IAM role to work with the secrets in the SSM Parameter Store"
    value: ${{  steps.environment.outputs.service-ssm-role }}
  service-config-ssm-path:
    description: "The path to the service configs in the SSM Parameter Store"
    value: ${{ steps.environment.outputs.service-config-ssm-path }}
  service-secret-ssm-path:
    description: "The path to the service secrets in the SSM Parameter Store"
    value: ${{ steps.environment.outputs.service-secret-ssm-path }}
  platform-ssm-path:
    description: "The path to the platform secrets per cluster in the SSM Parameter Store"
    value: ${{ steps.environment.outputs.platform-ssm-path }}
  cluster-role:
    description: "The IAM role to work with the cluster"
    value: ${{ steps.environment.outputs.cluster-role }}
  cluster:
    description: "The cluster to deploy to"
    value: ${{ steps.environment.outputs.cluster }}
  namespace:
    description: "The namespace"
    value: ${{ steps.environment.outputs.namespace }}
runs:
  using: "composite"
  steps:
    - name: Unique directory name
      shell: bash
      id: tmp
      run: |
        DIR=$(pwd)
        tmp_dir=$(mktemp -d --tmpdir=${DIR})
        echo "name=${tmp_dir}" >> $GITHUB_OUTPUT

    - name: Checkout Private actions
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.implementation_repository }}
        ref: ${{ inputs.implementation_ref }}
        token: ${{ inputs.implementation_github_pat }}
        path: ${{ steps.tmp.outputs.name }}

    - name: Copy action
      shell: bash
      run: |
        mv ${{ steps.tmp.outputs.name }}/${{ inputs.implementation_path }}/ ./.environment_implementation/

    - name: Environment Info
      uses: ./.environment_implementation
      id: environment
      with:
        environment: ${{ inputs.environment }}
        namespace: ${{ inputs.namespace }}
        config-app-name: ${{ inputs.config-app-name }}
        tenant: ${{ inputs.tenant }}
